#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation

personne_index:
    path: /person
    defaults: { _controller: 'App\Controller\PersonController::index' }

personne_new:
    path: /person/new
    defaults: { _controller: 'App\Controller\PersonController::new_' }

personne_new_two:
    path: /person/newtwo
    defaults: { _controller: 'App\Controller\PersonController::newGetPostAction' }

materiel_index:
    path: /material
    defaults: { _controller: 'App\Controller\MaterialController::index' }

materiel_new:
    path: /material/new
    defaults: { _controller: 'App\Controller\MaterialController::new_' }

materiel_new_two:
    path: /material/newtwo
    defaults: { _controller: 'App\Controller\MaterialController::newGetPostAction' }

inventory_index:
    path: /inventory
    defaults: { _controller: 'App\Controller\InventoryController::index' }

inventory_new:
    path: /inventory/new
    defaults: { _controller: 'App\Controller\InventoryController::new_' }

inventory_new_two:
    path: /inventory/newtwo
    defaults: { _controller: 'App\Controller\InventoryController::newGetPostAction' }

fight:
    path: /fight
    defaults: { _controller: 'App\Controller\FightController::indexAction' }

player_list:
    path: /
    defaults: { _controller: 'App\Controller\PlayerController::indexAction' }

player_new:
    path: /player_new
    defaults: { _controller: 'App\Controller\PlayerController::playerNew' }